# Generated by Django 4.0 on 2021-12-21 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('db', '0006_post_written_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='written_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='auth.user', verbose_name='Author'),
        ),
    ]
